# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Kubebuilder Installation
      uses: RyanSiu1995/kubebuilder-action@v1.3.1
      with:
        # Version of kubebuilder being installed
        version: '2.3.1'
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
